branch-defaults:
  master:
    environment: pothead-aws-dev
    group_suffix: null
global:
  application_name: pothead_aws
  branch: null
  default_ec2_keyname: pothead-keypair
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-southeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
